version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"

  server:
    build: .
    environment:
      - PG_STRING=${PG_STRING}
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: always
    ports:
      - "8082:8080"

volumes:
  pg_data:



